Fix movielist
MateuszBryczek/Movie-Browser pull request #18
Opened 2023-12-07 19:14 UTC by gosiagajlusz

I made like 20 previews,which were good,  so I hope this time it remain good looking in every device :)

2023-12-07 20:39 UTC, mombil requested changes
I think you should definitely change display flex and other styles with flex because not every element will need display flex in the future

2023-12-07 20:39 UTC, mombil commented on src/common/GlobalStyle.js
> +    display:flex;
Why you put display flex to GlobalStyle? These doesn't look right

2023-12-07 20:39 UTC, mombil commented on src/common/Header/styled.js
> +  /* justify-self: start; */
is this comment really necessary

2023-12-07 20:39 UTC, mombil commented on src/features/MovieList/MovieList.js
> +        <Pagination />
Pagination is back😄

2023-12-09 08:30 UTC, gosiagajlusz commented on src/common/GlobalStyle.js
> +    display:flex;
ok, in the end it wasn't necessary.

2023-12-09 08:32 UTC, gosiagajlusz commented on src/features/MovieList/MovieList.js
> +        <Header title="Popular movies"></Header>
what you mean?

2023-12-09 09:34 UTC, mombil commented on src/features/MovieList/MovieList.js
> +        <Header title="Popular movies"></Header>
sory i mean you can just give title beetwen header no as parameter

2023-12-09 13:13 UTC, gosiagajlusz commented on src/features/MovieList/MovieList.js
> +        <Header title="Popular movies"></Header>
Please explain what makes your solution better then current? Or what's wrong with current solution?

2023-12-09 19:01 UTC, mombil commented
Now it's look very good

2023-12-09 19:01 UTC, merged