MovieDetails
MateuszBryczek/Movie-Browser pull request #24
Opened 2023-12-09 15:54 UTC by MateuszBryczek

added MovieDetails page showing after clicking in movie tile (MovieDetailsLink in MovieCard).
currently not working as planned. after clicking shows correct link and throw back to movielist. After try to blocking Redirect freeze on loading after clicking.
I guess Navigation or MovieDetails code need fixes.
Error does not affect other elements of the page so further work is safe
I am ready for advices and review

2023-12-20 18:18 UTC, gosiagajlusz requested changes
I'm still looking for how error from peoplesaga should be fixed, but for now I wanted to send this, so you can fix it from your branch directly :)

2023-12-20 18:18 UTC, gosiagajlusz commented on src/features/MovieList/MovieCard/MovieCard.js
> -      </StyledCard>
you deleted  </StyledCard> closing tag, so it appears as error.

2023-12-20 18:18 UTC, gosiagajlusz commented on src/features/PeopleList/PeopleCard/PeopleCard.js
> +            </Description>
Opening tag is missing. So maybe  just <Descption/> would be ok

2023-12-21 09:03 UTC, gosiagajlusz approved these changes
now there are less errors ;)

2023-12-21 09:48 UTC, MateuszBryczek reviewed
MovieCard fixed but github doesn't show changes yet

2024-01-01 13:27 UTC, closed without merging