Pagination simplier
MateuszBryczek/Movie-Browser pull request #31
Opened 2023-12-28 16:15 UTC by gosiagajlusz

It works ok, changes pages, displayes correct page number, disablility works all right both for movies  and people. There is one thing I want to add later, perhabs from new branch: I am still thinking about how to make max pages  to be different depending on true value of total_pages in api.  We have lots of changes to merge, so I don't want to wait with it until this merge will be extremly complicated due to changes everyone else is doing in the meantime ;)

2023-12-29 10:30 UTC, mombil requested changes
You should fix errors and merge to your own branch because you have many conflicts and this can cause new errors

2023-12-29 10:30 UTC, mombil commented on src/common/Pagination/index.js
> +const Pagination = ({ isMovieList, total_pages }) => {
you should not get isMovieList from movieList and PeopleList. It would be better if you make it with useLocation.pathname

2023-12-29 10:30 UTC, mombil commented on src/common/Pagination/styled.js
> +
too many new lines

2023-12-29 10:30 UTC, mombil commented on src/features/MovieList/MovieList.js
> +            <Pagination isMovieList={true}/>
like i said it should not be transmitted to pagination in this way

2023-12-29 10:30 UTC, mombil commented on src/features/MovieList/getMovies.js
> +  const { data } = await axios.get(`${popularMoviesURL}` + `${moviePage}`);
why you using in getMovies axios and in onther config decide what is better and this with one thing

2023-12-29 10:30 UTC, mombil commented on src/features/MovieList/MovieList.js
> +  selectMaxMoviePages
'setMaxPeoplePages' is defined but never used

2023-12-29 10:30 UTC, mombil commented on src/features/MovieList/getMovies.js
> +import { apiKey } from "../config";
'apiKey' is defined but never used

2023-12-29 10:30 UTC, mombil commented on src/features/MovieList/getMovies.js
> +import { basicUrl } from "../config";
'basicUrl' is defined but never used

2023-12-29 10:30 UTC, mombil commented on src/features/MovieList/getMovies.js
> +  const { data } = await axios.get(`${popularMoviesURL}` + `${moviePage}`);
you can also do this by  
  const { data } = await axios.get(popularMoviesURL + moviePage);

2023-12-29 10:30 UTC, mombil commented on src/features/MovieList/movieSaga.js
> +  setMaxMoviePages,
'setMaxMoviePages' is defined but never used

2023-12-29 10:30 UTC, mombil commented on src/features/PeopleList/PeopleList.js
> +  setMaxPeoplePages,
'setMaxPeoplePages' is defined but never used

2023-12-29 10:30 UTC, mombil commented on src/features/PeopleList/PeopleList.js
> +            <Pagination isPeopleList={true}/>
you dont even use isPeopleList in pagination

2023-12-29 10:30 UTC, mombil commented on src/features/PeopleList/getPeople.js
> +  const { data } = await axios.get(`${popularPeopleURL}` + `${peoplePage}`);
here you can do this with   
const { data } = await axios.get(popularPeopleURL + peoplePage);

2023-12-29 10:30 UTC, mombil commented on src/features/PeopleList/peopleSaga.js
> +      const people = yield call(getSearchedPeople, searchValue, peopleId, page);
here you have to change order because people  search not working. try this:
const people = yield call(getSearchedPeople, searchValue, page, peopleId);

2023-12-29 11:02 UTC, gosiagajlusz commented
It's weird because I don't even have one error. Although people search actually doesn't work, I thought it's just not done yet. So'll fix it and change my shortcut to useLocation pathname. Don't really know how to fix errors which only you have ;) I will commit again after changes and we will see what's left from them.

2023-12-29 11:07 UTC, gosiagajlusz commented on src/features/PeopleList/peopleSaga.js
> +      const people = yield call(getSearchedPeople, searchValue, peopleId, page);
I just forgot to rename page

2023-12-30 16:53 UTC, gosiagajlusz commented on src/common/Pagination/index.js
> +const Pagination = ({ isMovieList, total_pages }) => {
changed

2023-12-30 16:54 UTC, gosiagajlusz commented on src/common/Pagination/styled.js
> +
fair enough

2023-12-30 16:54 UTC, gosiagajlusz commented on src/features/MovieList/MovieList.js
> +            <Pagination isMovieList={true}/>
ok

2023-12-30 17:28 UTC, gosiagajlusz commented on src/features/MovieList/getMovies.js
> +  const { data } = await axios.get(`${popularMoviesURL}` + `${moviePage}`);
i unified it everywhere except for genras because its to complcated to do it before merge and i am not reallly sure idf its necessary

2023-12-30 17:29 UTC, gosiagajlusz commented on src/features/MovieList/MovieList.js
> +  selectMaxMoviePages
i've deleted everything unused

2023-12-30 17:34 UTC, gosiagajlusz commented on src/features/PeopleList/PeopleList.js
> +            <Pagination isPeopleList={true}/>
true

2023-12-30 17:34 UTC, gosiagajlusz commented on src/features/PeopleList/getPeople.js
> +  const { data } = await axios.get(`${popularPeopleURL}` + `${peoplePage}`);
ok its everywhere unified

2023-12-30 19:56 UTC, MateuszBryczek approved these changes

2023-12-30 19:56 UTC, MateuszBryczek commented on src/features/MovieList/getMovies.js
> +  const { data } = await axios.get(`${popularMoviesURL}` + `${moviePage}`);
everywhere we use "config" instead of "axios" so i think you can change that

2023-12-30 19:56 UTC, MateuszBryczek commented on src/features/MovieList/getMovies.js
> +  const { data } = await axios.get(`${popularMoviesURL}` + `${moviePage}`);
i see now why, its ok

2023-12-30 19:58 UTC, merged